### ISSUE TITLE
db hint

### ISSUE THREAD

**Issue by vitaly-t** [heyEllex/pdfgen#1]
you really should start using [Query Files](https://github.com/vitaly-t/pg-promise#query-files), your query in JavaScript looks ridiculous :)

Not to mention it can save great deal of time developing the query while running the process (see property `debug`) :wink:

**Comment by heyEllex** [comment]
I was already thinking about this, thank you for hint, will do it for sure :)

**Comment by vitaly-t** [comment]
It also help a lot to using named variables rather than numbers ;)
